### ISSUE TITLE
Can't find player on first join

### ISSUE THREAD

**Issue by hockeymikey** [jmhertlein/MCTowns#67]
I can't add a player to a town if they joined the server for the first time, it says they can not be found.  They can be added after relogging.

**Comment by jmhertlein** [comment]
Ah yeah, error is here: https://github.com/jmhertlein/MCTowns/blob/dev/src/main/java/net/jmhertlein/mctowns/command/handlers/TownHandler.java#L368

The intent of this line is to prevent you from accidentally adding a typo'd version of the name of a player who's offline.

I'll fix this shortly

**Comment by jmhertlein** [comment]
fixed in 6850ddf6b26d6d35d017f1fbd7a765e2fc04ab08

new jar can be found here: http://jmhertlein.net:8080/job/MCTowns/44/net.jmhertlein$MCTowns/

**Comment by hockeymikey** [comment]
Thanks you work quick!  I'm busy for the next couple days but I'll try to test this when I have a chance and see if it's resolved.  By looking at your code it would seem that it would work, in theory.
