### ISSUE TITLE
Town Warps

### ISSUE THREAD

**Issue by hockeymikey** [jmhertlein/MCTowns#70]
A town warp would be a public warp that all members of that town can use.
You must be an assistant or mayor to set a town warp.

/town list warps

/town setwarp (name)

/town warp (name)

**Comment by jmhertlein** [comment]
Is this not already a thing?

`/town spawn`

`/town spawn set`

Requires the mct.warp permission node to use the warp, though.

**Comment by hockeymikey** [comment]
But that is only one warp, a spawn for your town while you can set an unlimited (Not literal) number of warps to other points of interest in the town that people want to go to.  
For example lets say you have a territory that is part of the town far away.  You can set a warp to there and anyone in the town can use it.

**Comment by jmhertlein** [comment]
Oh I understand that you mean. Sure, that's definitely doable.

**Comment by hockeymikey** [comment]
Fantastic thanks!
