### ISSUE TITLE
McTown Command not working

### ISSUE THREAD

**Issue by tristankhalil** [jmhertlein/MCTowns#72]
Hello, 

I'm not sure what I missed but when I try to type /mct addtown TownName @p , it just return me the mct command set (variables and params).

I did make sure to put proper perm nodes and me as OP/Owner rank.

May I know what I'm missing?

**Comment by jmhertlein** [comment]
Check your server logs for any error messages.

Do you have the dependencies installed (WorldGuard and WorldEdit)? 

https://github.com/jmhertlein/MCTowns/wiki/Download-Methods#dependencies

**Comment by tristankhalil** [comment]
Hello, 

Here's the server log and I just noticed now it says: 

[08:30:39] [Server thread/INFO]: [MCTowns] Enabling MCTowns v2.4.0-6650f896d5e388047388965084ae7cf0282086da
[08:30:39] [Server thread/INFO]: [MCTowns] Detected resources to be those generated by v2.4.0
[08:30:39] [Server thread/INFO]: [MCTowns] Resources are up to date.
[08:30:39] [Server thread/ERROR]: Error occurred while enabling MCTowns v2.4.0-6650f896d5e388047388965084ae7cf0282086da (Is it up to date?)

here's the full server log: http://pastebin.com/Da2uQqcs

**Comment by jmhertlein** [comment]
You do not have the correct version of WorldGuard. The update from WorldGuard 5.9 to 6.0 broke compatibility and MCTowns v2.4.0 requires WorldGuard 6.0

Please update WorldGuard: http://dev.bukkit.org/bukkit-plugins/worldguard/files/

**Comment by tristankhalil** [comment]
Yay it work now. 

Another question: will it shows the rank of Mayor, Assistant Mayor and Residents?

**Comment by jmhertlein** [comment]
MCTowns does not currently support chat prefixes. See issue #71 for details on the feature request.
