### ISSUE TITLE
[Wiki] Add Region Flag Setup and  Assigning Assistant Mayors

### ISSUE THREAD

**Issue by tristankhalil** [jmhertlein/MCTowns#73]
I was browsing the wiki and I can't find how to set region flag for my new town/territory.

The reason for this is because my server is setup to have PVP. But my town will be a peaceful town (means no PVP) with a special PVP Arena (to be added later with another region flag maybe).

And may I know how to set Assistant Mayors? Can this player be an Assistant Mayor of other towns?

**Comment by jmhertlein** [comment]
`/town add assistant <name>`

If you change config.yml to allow players to join multiple towns, then yes, they can.

To flag a territory, you can either do:

`/territory flag pvp deny` or `/region flag <townname>_territ_<territory name> pvp deny`

MCTowns doesn't do anything too hacky with WorldGuard and is careful not to store data that's already in the region (and so might get "out of sync"), so if you need to you can do anything you want to the WorldGuard regions as long as you do not delete them (or rename them).

**Comment by tristankhalil** [comment]
Thank you for the quick response.

I was also planning to deny mob-spawn but allow animal spawn, not sure if that is doable. I'm not knowledgeable with WorldGuard hence I'm here asking about the flags that is doable for my town.

**Comment by jmhertlein** [comment]
http://wiki.sk89q.com/wiki/WorldGuard/Regions/Flags#Flag_List

MCTowns puts a lot of effort into making sure that all the features of WorldGuard are fully supported (non-cuboid regions, all the flags, etc). So if it's in that list, MCTowns supports it.

**Comment by tristankhalil** [comment]
Thank you!
