### ISSUE TITLE
Invalid commands?

### ISSUE THREAD

**Issue by tristankhalil** [jmhertlein/MCTowns#74]
Hello, I tried to do the following:

/mct info player <player name>
Prints information about the specified player.

/mct info town <town name>
Prints information about the specified town.

I got an error: Invalid commands. Acceptable similar formats are: /mct info (player | town)

---- Update ---

Add /mct list request

**Comment by jmhertlein** [comment]
it's

`/mct info player <playername>`

and `/mct info town <town name>`

And I think `/mct list requests` is a command I don't have added. The arguments for `/mct list` are "towns" and "invite"

**Comment by tristankhalil** [comment]
Oh ok got it.
