### ISSUE TITLE
Maven, dev builds

### ISSUE THREAD

**Issue by hockeymikey** [jmhertlein/MCTowns#81]
Could you fix your jenkins so that the dev builds are downloadable.

Also can every dev build that is included be available in your maven responsibility along with just more in general because 2.3 is pretty old to build against considering you released UUIDs in 2.4 (and possibility changing methods I believe too).

Thanks

**Comment by hockeymikey** [comment]
Also update the JavaDocs to atleast 2.4 since I think you removed player lookup methods.

**Comment by jmhertlein** [comment]
Sure. I didn't think anyone used my maven repo or the jd's.

The dev builds on jenkins should be downloadable?

Try this:
http://jmhertlein.net:8080/job/MCTowns/lastBuild/net.jmhertlein$MCTowns/

and click on the jar artifact.

**Comment by jmhertlein** [comment]
I've got the maven repo updated, will push jd's tomorrow.

**Comment by hockeymikey** [comment]
Yeah I might be the only one (as far as I know).

Thanks, totally missed the obvious download links.

**Comment by hockeymikey** [comment]
Quick question, where was TownManager moved to?

**Comment by hockeymikey** [comment]
Nevermind, found it.
