### ISSUE TITLE
Maven broken

### ISSUE THREAD

**Issue by hockeymikey** [jmhertlein/MCTowns#83]
Looks like your maven broke and I can't find MCTowns in there.

**Comment by jmhertlein** [comment]
Working on it- the connection info/path has actually changed as well. See this pom for details:

https://github.com/jmhertlein/reflective/blob/master/pom.xml

I still need to re-upload the jars though. Will keep you posted.

**Comment by jmhertlein** [comment]
Sorry this has been taking so long. Very busy lately. I hardened my ssh installation on the maven server a few weeks ago and it looks like wagon-ssh can't handle 'modern' encryption. Will have to work around it.

Also working on getting maven.jmhertlein.net whitelisted for the Let's Encrypt beta so using HTTPS will work for real.

**Comment by jmhertlein** [comment]
Alrighty- sorry this took basically a month, but MCTowns is now available on maven.jmhertlein.net again.

Additionally, you should now use HTTPS to access the repo, as seen here:

    <repository>
      <id>jmh-repo</id>
      <url>http://maven.jmhertlein.net/~joshua/maven/</url>
    </repository>

**Comment by hockeymikey** [comment]
Thanks, still using HTTP to access since Let'sEncrypt isn't trusted by java and it was more work than it was worth to fix.
