### ISSUE TITLE
Town bank currency

### ISSUE THREAD

**Issue by Okervill** [jmhertlein/MCTowns#89]
Currently people can donate ridiculous amounts to the town banks like 1.0000000000000007 which causes an issue if it goes too far because once that many decimals are there they won't go away unless you manually edit the config file. 

If you limited it to 2 decimal places or rounded up that'd be great. Then it would also nicely tie into essentials which only displays 2

**Comment by jmhertlein** [comment]
I'll probably make it a config option. It's unfortunate that currency in Minecraft is so non-standard, because I know some people use "BTC" as their currency and trading thousandths  (or smaller) of a unit of currency does make sense in that case.

**Comment by Okervill** [comment]
Ahh fair enough, appreciate the quick reply though.
It's just annoying that if i put in 1.0000000000005, then remove the 0.0000000000005 it'll still stay i have 1.0000000000000.
Thanks though

**Comment by jmhertlein** [comment]
Yeah, to clarify, I will put in a config option that defaults to 2 digits of precision. And, that's odd, I would expect it to collapse back down to 1. I'll look into that.
